In [1]:
import numpy as np

In [24]:
neighbors = np.array([[0, 1], [1, 0], [-1, 0]])

In [28]:
C = neighbors.dot(np.transpose(neighbors))
print(C)

print("\nMinimal distance")
evl, evc = np.linalg.eig(C)
ix = np.argmin(evl)
evc = evc[ix]
# evc = evc / np.sum(evc)
print(evl[ix])
print(evc)

print("\nReconstructed zero")
print(np.expand_dims(evc, -1))
# print(np.sum(np.expand_dims(evc, -1) * neighbors, 0))

[[ 1  0  0]
 [ 0  1 -1]
 [ 0 -1  1]]

Minimal distance
0.0
[-0.70710678  0.70710678  0.        ]

Reconstructed zero
[[-0.70710678]
 [ 0.70710678]
 [ 0.        ]]
